###############################################
# TITLE: Velez's Dictionary Look-up: Latin lemmas
# DESCRIPTION: Searches the lemma bank for a given string and returns the lexical entries linked to it.
###############################################

PREFIX lexicog: <http://www.w3.org/ns/lemon/lexicog#>
PREFIX lex: <http://purl.org/lex#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lila: <http://lila-erc.eu/ontologies/lila/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX lime: <http://www.w3.org/ns/lemon/lime#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX lexinfo: <http://www.lexinfo.net/ontology/2.0/lexinfo#>
PREFIX skos: <http://www.w3.org/2004/02/skos#>
PREFIX lemma: <http://lila-erc.eu/data/id/lemma/>

# INSTRUCTION: For changing the queried word, replace 'do' with the desired lemma inside the string '^__$' at line 23.

SELECT (group_concat(distinct ?lemmaWrittenRep ; separator=", ") as ?lema) (?definition as ?definição) (?posdefNote as ?comentário) (?exampleText as ?exemplo) (?PoS as ?classe) ?lemmaURI
WHERE 
{   
  FILTER regex(?lemmaWrittenRep, "^do$")
  <http://lila-erc.eu/data/lexicalResources/LatinPortuguese/Velez/Lexicon> lime:entry  ?lexentry.
  ?lexentry ontolex:canonicalForm ?lemmaURI ;
            ontolex:sense ?senseURI .
  ?lemmaURI rdfs:label ?lemma ;
            lila:hasPOS ?PoS ;
            ontolex:writtenRep ?lemmaWrittenRep .
  ?senseURI rdf:type ontolex:LexicalSense .
  ?senseURI skos:definition ?definition .
  optional {
      ?senseURI lexinfo:note ?posdefNote .
  }
  optional {
      ?senseURI lexicog:usageExample ?exampleURI .
	  ?exampleURI rdfs:label ?exampleText .
  }
}
order by ?senseURI ?exampleURI
